### ISSUE TITLE
sampledata4에 대한 다른 분석 결과 입니다

### ISSUE THREAD

**Issue by hanyangunivleejoohyun** [Jason-Kim/dossier#2]
![error_1](https://cloud.githubusercontent.com/assets/19625332/26571897/d8778b94-4552-11e7-810e-4d62de8e388c.png)
![result_1](https://cloud.githubusercontent.com/assets/19625332/26571899/d87b0850-4552-11e7-8303-eafd4f003dcf.png)
워드 클라우드 분석시 1번과 같은 메세지가 뜨고 대기를 누르고 기다려야 출력이 되는 경우도 있고
메세지가 안 뜨고 결과가 나오는 경우도 있습니다.
현재는 안 뜨고 있습니다. 일단은 신경쓰지  않으셔도 될 것 같습니다.

그리고 2번 그림처럼 결과가 읽기 어렵게 표시되고 시간이 오래걸려서
    dtm <- removeSparseTerms(dtm, 0.99)
코드 삽입해 놓았습니다. 확실히 분석시간은 단축되었습니다.

그리고 kwic 분석에서 
unused arguments (window = window, valuetype = value_type)
에러 메세지가 나타납니다. 
이 에러도 발생하다가 발생 안 하다가 해서 조금 더 알아보겠습니다.

--------------------------------------------------------------------------------------------------------------

![error_2](https://cloud.githubusercontent.com/assets/19625332/26571898/d879f2ee-4552-11e7-8155-4c2d1b1a2237.png)
arules_group 함수 실행 부분에서 위와 같은 에러 메세지가 나타나면서 샤이니가 꺼지는 현상이 발생합니다. 그래서 코드로 실행해 봤는데 역시 완료되지 않고 연결이 끊어지는 현상이 발생합니다.
그런데 arules_graph는 잘 실행 되고 결과 plot이 도출됩니다.

--------------------------------------------------------------------------------------------------------------

![result_2](https://cloud.githubusercontent.com/assets/19625332/26571900/d87d4c96-4552-11e7-8e47-51d6e4485ec9.png)
bib에서 Y축이 위 사진과 같이 출력 되어서 식별이 어렵습니다. 
빈도수가 높은 상위의 몇 가지만 출력해야 할 것 같습니다.

--------------------------------------------------------------------------------------------------------------

도시에 DB 다운로드 관련해서 여쭤봤는데 다운로드 기능은 아직 없다고 하셨습니다.
저희가 하는 프로젝트에서 다운로드가 필요한 부분인지에 대한 커뮤니케이션이 잘 되지 않은 것 같습니다.
일단은 다운로드 기능은 없다고 하십니다.

**Comment by hanyangunivleejoohyun** [comment]
@Jason-Kim 어제 말씀하셨던 부분 결과 입니다 !

**Comment by Jason-Kim** [comment]
오전에 rstudio-server가 무응답상태가 잠깐 있었어요.. 혹시 그것과 관련된건 아닌가 싶네요..

**Comment by hanyangunivleejoohyun** [comment]
아마도 그런 것 같습니다. 코드 상의 오류는 아닌 것 같긴 했습니다.
kwic분석 관련해서는 좀 더 살펴보고 다시 말씀드리겠습니다.

**Comment by hanyangunivleejoohyun** [comment]
kwic 문제 해결했습니다. kwic함수가 따로 만들어서 선언이 되어 있어서 에러가 난 것 같습니다.

rm()으로 kwic 함수 삭제하고 재실행 해서 해결했습니다.

**Comment by Jason-Kim** [comment]
네, 충돌이 있었나 보네요..

**Comment by hanyangunivleejoohyun** [comment]
예 그런 것 같습니다.
다른 것들도 보고 다시 말씀드리겠습니다.
