### ISSUE TITLE
연도별 출원 지도 플롯 관련 이슈

### ISSUE THREAD

**Issue by hanyangunivleejoohyun** [Jason-Kim/dossier#3]
@jwlee0801 책임님 어제 공유해주신 분석 관련해서 몇 가지 말씀드릴 것이 있습니다.

먼저  cntByapp.R에서 
```r
dat<-function(df){
  a<-substr(df.org$출원번호,4,7)
  l<-gsub(".*,\\s*|\\).*", "", trimws(df.org$출원인))
```
부분에서 함수 안에서는 df.org로 접근하는데 함수 선언부에서 인수를 df를 받는 오타 있습니다.
혹시 충돌 날까봐 제가 수정은 안하고 말씀드립니다!

그리고 혹시 어제 말씀드렸던 지도 플롯 그리는 부분에서

연도 범위를 리턴하는 부분이 어느 부분인지 알려주시면 감사하겠습니다.
===
dat<-function(df.org)로 받아야 되는데 오타가 있었네요.
연도는 dat()의 리턴값을 dt<-dat(df.org)라고 하였을 때 min(names(dt))을 최솟값, max(names(dt))를 최댓값으로 설정하여 주시면 됩니다. 
감사합니다.

**Comment by hanyangunivleejoohyun** [comment]
혹시 cntByapp 파일 수정 안하시면 제가 수정해서 푸쉬하겠습니다

**Comment by jwlee0801** [comment]
@hanyangunivleejoohyun 

dat<-function(df.org)로 받아야 되는데 오타가 있었네요.
연도는 dat()의 리턴값을 dt<-dat(df.org)라고 하였을 때 min(names(dt))을 최솟값, max(names(dt))를 최댓값으로 설정하여 주시면 됩니다. 
감사합니다.
